### PR TITLE
image classes and min-width media support

### PR DESCRIPTION
**Pull request by lukepearce**
Feel free to refactor the min/max media mixin. The default value is set to max so all existing instances of ```@include media( $condition )``` won't be affected.

### CODE REVIEW

**Comment by andygrn** [comment]
Image classes I am happy with - but can you give me an example of something done with min-width that can't be done with max-width?

**Comment by lukepearce** [comment]
min-width is helpful to restrict un-doing of earlier set css...

```
&__right {
			@include media( palm-, min ) {
				float: right;
			}
	  	@include media( lap-, min ) {
	  		margin-top: 7px;
			}
		}
```

In this example the class ```.header__right``` only inherits the property ```text-align: right``` once the window is larger than the ```palm-``` breakpoint.

If I had to do that with max-width I'd need to set ```text-align: left``` which only serves to overide CSS and restore a default value.

Similarly, ```.header__right``` only requires a ```margin-top``` value on breakpoints over ```lap-``` width. I find it makes more sense to only set the CSS when it's needed instead of resetting it.

**Comment by lukepearce** [comment]
It's also extremely helpful when the amount of styles you'd have to undo increase... take this for example

```
&__text {
  text-align: center;
    @include media( lap- ) {
       margin-bottom: $type-base-size;
       padding: $type-base-size;
     }
     @include media( lap-, min ) {
       position: absolute;
       bottom: -20%;
       opacity: 0;
       left: 0;
       right: 0;
       background: $colour-link;
       padding: $type-base-size * 2;
       transition: all 300ms ease-in-out;
         .h {
           color: #fff;
         }
   }
```

A mobile browser is only going to need to read text-align: center and the values in the ```@include media( lap- )``` rule instead of undoing all the rules in the ```@include media( lap-, min )``` rule.... much less code and much less hassle.

**Comment by lukepearce** [comment]
GIVE ME ATTENTION!!!

take me seriously

**Pull request closed without merging**
